### ISSUE TITLE
Github actions has removed homebrew support

### ISSUE THREAD

**Issue by chrischildresssg** [StratusGrid/workflow-config#20]
## Expected Behavior
During workflow pipeline, Homebrew installs necessary tools such as tfenv, terraform-docs, tflint.

## Actual Behavior
Scripts fail upon trying to run homebrew (no command "brew" found).  This is caused by "brew" not being located in the PATH of the existing system.

## Suggested mitigations

  1. Remove homebrew completely from the configuration

**Comment by JoseMotto-sg** [comment]
Fixed in https://github.com/StratusGrid/workflow-config/pull/19
