### ISSUE TITLE
Workflow config requires .terraform-version

### ISSUE THREAD

**Issue by rchildress87** [StratusGrid/workflow-config#27]
## Expected Behavior

A well-written Terraform project that references this publicly available GitHub workflow will pass all GitHub Actions jobs defined in the workflow without defining a Terraform version for tfenv, a tool which may not be needed.

## Actual Behavior

GitHub Actions jobs `terraform_ftm` and `terraform_validate` fail if no .terraform-version file in included in the top-level of the repo.

## Steps to Reproduce the Problem

  1. Trigger GitHub actions on a branch of this repo that does not include .terraform-version but is otherwise valid, formatted, and secure HCL.

## Specifications

 - Version: workflow-config 0.9.1

**Comment by rchildress87** [comment]
I'm going to PR a change that adds logic to both `tfenv install` and `tfenv use` when no Terraform version is explicitly defined in a .terraform-version file.

**Comment by JoseMotto-sg** [comment]
I think that we can close this @rchildress87
