### ISSUE TITLE
GitHub Actions jobs use v0.1 of .pre-commit-config.yaml

### ISSUE THREAD

**Issue by rchildress87** [StratusGrid/workflow-config#29]
## Expected Behavior

Each job should use the latest release version of .pre-commit.config.yaml

## Actual Behavior

Each job uses v0.1 of .pre-commit.config.yaml

## Steps to Reproduce the Problem

  1. Trigger a GitHub Actions workflow on a branch that uses this workflow-config project.

## Specifications

  - Version: workflow-config v0.9.1

**Comment by rchildress87** [comment]
The GitHub pre-commit workflow uses an environment variable, `WORKFLOW_VERSION`, that is currently set to `v0.1`. This environment variable is used to define the git `ref` in the "Checkout precommit config" step of each job of the defined workflow that uses pre-commit.

Because our default branch, `main`, should always represent the latest release of this workflow, I suggest we remove `WORKFLOW_VERSION` and relevant `ref`'s from the config entirely.

**Comment by JoseMotto-sg** [comment]
I think that we can close this, @rchildress87
