### ISSUE TITLE
Right source for the integration of trivy in the pre-commit

### ISSUE THREAD

**Issue by jheison-rodriguez** [StratusGrid/workflow-config#70]
## Expected Behavior
There is a built-in pre-commit plugin for Trivy
https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_trivy

## Actual Behavior
We are using other source to integrate trivy in the pre-commit
https://github.com/mxab/pre-commit-trivy

Is there any specific reason for this?
@JoseMotto-sg

**Comment by JoseMotto-sg** [comment]
Yes, the official accepted pre-commit from  Aqua Security is the one we are using right now
Check https://aquasecurity.github.io/trivy/v0.49/ecosystem/ide/
@jheison-rodriguez

**Comment by jheison-rodriguez** [comment]
👍
